[package]
name = "wasmi_benches_tiny_keccak"
version = "0.0.0"
publish = false
authors.workspace = true
edition.workspace = true

[lib]
path = "lib.rs"
crate-type = ["cdylib"]

[dependencies]
tiny-keccak = { version = "2.0.2", features = ["keccak"] }
