[package]
name = "wasmi_benches_regex_redux"
version = "0.0.0"
publish = false
authors.workspace = true
edition.workspace = true

[lib]
path = "lib.rs"
crate-type = ["cdylib"]

[dependencies]
regex = "1.10.5"
