[build]
rustflags = [
    # This flag is extremely important to make LLVM _not_ pessimize
    # codegen for the conversion of `OpCode` to execution handler.
    # This resulted in massive wins for compile-time and execution
    # performance, especially when `indirect-dispatch` is enabled.
    #
    # Tested with: Rust 1.96 using LLVM 22.1.2
    "-C",
    "llvm-args=--switch-to-lookup=true",
]
