(module
  (func (;0;) (param i32 i32) (result i32)
    (local $tmp i32)
    (local.get 0)
    (local.get 1)
    (local.set 1 (i32.const 10))
    (local.set 0 (i32.const 20))
    (if (param i32 i32) (result i32)
      (local.get 0)
      (then
        (i32.add)
        (local.get $tmp)
        (local.set $tmp (i32.const 30))
        (drop)
      )
      (else
        (i32.mul)
      )
    )
  )
)
